#%RAML 0.8
title: OICBodyTemperature
version: v1.1.0-20160519
documentation:
  - title: © 2017 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - BodyTemperature:  !include schemas/oic.r.body.temperature-obs.json
  - BodyTemperature-ll: !include schemas/oic.r.body.temperature-obs-ll.json
  - BodyTemperature-b: !include schemas/oic.r.body.temperature-obs-b.json

traits:
  - interface-baseline:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

  - interface-ll:
      queryParameters:
        if:
          enum: ["oic.if.ll"]

  - interface-b:
      queryParameters:
        if:
          enum: ["oic.if.b"]

/BodyTemperatureBaselineResURI?if=oic.if.baseline:
  description: |
    This resource describes the proporties associated with body temperature.
    The resource is a collection of Temperature (oic.r.temperature), Body Location (oic.r.body.location), and Clock (oic.r.clock).

  displayName: Body temperature
  is: [ interface-baseline ]

  get:
    description: |
      Retrieves the current body temperature.
    responses:
      200:
        body:
          application/json:
            schema: BodyTemperature
            example: |
              {
                "rt":   ["oic.r.body.temperature-obs", "oic.wk.col", "oic.r.atomic"],
                "if":   ["oic.if.baseline","oic.if.ll", "oic.if.b"],
                "id":   "unique_example_id",
                "links": [
                  { "href": "/myTemperatureResURI", "rt": ["oic.r.temperature"], "if": ["oic.if.s", "oic.if.r", "oic.if.baseline"] },
                  { "href": "/myBodyLocationResURI", "rt": ["oic.r.body.location"], "if": ["oic.if.s", "oic.if.r", "oic.if.baseline"] },
                  { "href": "/myClockResURI", "rt": ["oic.r.clock"], "if": ["oic.if.s", "oic.if.r", "oic.if.baseline"] }
                ]
              }

/BodyTemperatureLLResURI?if=oic.if.ll:
  description: |
    This resource describes the proporties associated with body temperature.
    The resource is a collection of Temperature (oic.r.temperature), Body Location (oic.r.body.location), and Clock (oic.r.clock).

  displayName: Body temperature
  is: [ interface-ll ]

  get:
    description: |
      Retrieves the current body temperature.
    responses:
      200:
        body:
          application/json:
            schema: BodyTemperature-ll
            example: |
              {
                "links": [
                  {"href": "/myTemperatureResURI", "rt": ["oic.r.temperature"], "if": ["oic.if.s", "oic.if.r", "oic.if.baseline"]},
                  {"href": "/myBodyLocationResURI", "rt": ["oic.r.body.location"], "if": ["oic.if.s", "oic.if.r", "oic.if.baseline"]},
                  {"href": "/myClockResURI", "rt": ["oic.r.clock"], "if": ["oic.if.s", "oic.if.r", "oic.if.baseline"]}
                ]
              }

/BodyTemperatureBatchResURI?if=oic.if.b:
  description: |
    This resource describes the proporties associated with body temperature.
    The resource is a collection of Temperature (oic.r.temperature), Body Location (oic.r.body.location), and Clock (oic.r.clock).

  displayName: Body temperature
  is: [ interface-b ]

  get:
    description: |
      Retrieves the current body temperature. and associated properties atomically as a batch
    responses:
      200:
        body:
          application/json:
            schema: BodyTemperature-b
            example: |
              [
                {
                  "href": "/myTemperatureResURI",
                  "rep": {
                    "temperature": 37
                  }
                },
                {
                  "href": "/myBodyLocationResURI",
                  "rep": {
                    "bloc": "finger"
                  }
                },
                {
                  "href": "/myClockResURI",
                  "rep": {
                    "datetime": "2007-04-05T14:30+09:00"
                  }
                }
              ]
