#%RAML 0.8
#RAML for OIC Collections.
# This is an initial version; has to be converted to a RAML resource type so that it can be used when defining resource that
# are collections. Also needs to use traits to have the same query parameters recognized for all the methods.
title: OCF Luminaire
version: 0.1
documentation:

  - title: OCF Luminaire
    content: |
      Luminaire model using the composite collection resource design

  - title: Introduction
    content: |
      Luminaire modeled after a common lighting capability set,
      composed from standard OCF resource types

  - title: Resource Design
    content: |
      The collection resource is specified as three Base URIs, one
      for each interface which is supported by the collection

      These three URIs are the same URI path, distinguished
      by the different query parameter traits

schemas:
  - sbaseline: !include schemas/oic.r.luminaire.schema-baseline.json
  - sbatch: !include schemas/oic.r.luminaire.schema-b.json
  - slinks: !include schemas/oic.r.luminaire.schema-ll.json

traits:
  - interface-baseline:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

  - interface-b:
      queryParameters:
        if:
          enum: ["oic.if.b"]

  - interface-ll:
      queryParameters:
        if:
          enum: ["oic.if.ll"]


/LuminaireBaselineInterfaceURI:
  description: |
    OCF Collection Resource Type contains properties and links.
    The oic.if.baseline interface exposes a representation of
    the links and the properties of the collection resource itself


  displayName: OCF Luminaire
  is: [ interface-baseline ]

  get:
    description: |
      Retrieve on Baseline Interface

    responses:
      200:
        body:
          application/json:
            schema: sbaseline
            example: |
              {
                "rt": ["oic.wk.col", "oic.r.luminaire"],
                "if": ["oic.if.baseline", "oic.if.b", "oic.if.ll"],
                "rts": ["oic.r.binaryswitch", "oic.r.brightness" , "oic.r.colourcontrol", "oic.r.ramptime", "oic.r.actuation"],
                "links": [
                  {
                    "href": "switch",
                    "ins": "switch",
                    "title": "On/Off Switch",
                    "rt":   ["oic.r.binaryswitch"],
                    "if":   ["oic.if.a", "oic.if.baseline"]
                  },
                  {
                    "href": "level",
                    "ins": "level",
                    "title": "Brightness Level",
                    "rt":   ["oic.r.brightness"],
                    "if":   ["oic.if.a", "oic.if.baseline"]
                  },
                  {
                    "href": "colorcontrol",
                    "ins": "colorcontrol",
                    "title": "Color Control",
                    "rt":   ["oic.r.colourchroma"],
                    "if":   ["oic.if.a", "oic.if.baseline"]
                  },
                  {
                    "href": "colortemperature",
                    "ins": "colortemperature",
                    "title": "Color Temperature",
                    "rt":   ["oic.r.colourchroma"],
                    "if":   ["oic.if.a", "oic.if.baseline"]
                  },
                  {
                    "href": "ramptime",
                    "ins": "ramptime",
                    "title": "Ramp Time",
                    "rt":   ["oic.r.ramptime"],
                    "if":   ["oic.if.a", "oic.if.baseline"]
                  },
                  {
                    "href": "actuation",
                    "rel": "actuator",
                    "ins": "actuation",
                    "title": "Actuation",
                    "rt":   ["oic.r.actuation", "oic.r.binaryswitch", "oic.r.brightness", "oic.r.colourchroma", "oic.r.ramptime"],
                    "if":   ["oic.if.a", "oic.if.baseline"]
                  }
                ]
              }

  post:
    description: |
      Update on Baseline Interface

    body:
      application/json:
        schema: sbaseline

    responses:
      200:
        body:
          application/json:
            schema: sbaseline


/LuminaireBatchInterfaceURI:
    description: |
      The oic.if.b interfacce exposes a composite representation of the
      resources pointed to by the links

    displayName: Batch Representation
    is: [ interface-b ]

    get:
      description: |
        Retrieve on Batch Interface

      responses:
        200:
          description: "All targets returned OK status (HTTP 200 or CoAP 2.05 Content)"
          body:
            application/json:
              schema: sbatch
              example: |
                [
                  {
                    "href": "switch",
                    "rep":
                      {
                        "value": true
                      }
                  },
                  {
                    "href": "level",
                    "rep":
                      {
                        "brightness": 77
                      }
                  }
                ]

        404:
          description: "One or more targets did not return an OK status, return a representation containing returned properties from the targets that returned OK"
          body:
            application/json:
              schema: sbatch
              example: |
                [
                  {
                    "href": "switch",
                    "rep":
                      {
                        "value": false
                      }
                  }
                ]

    post:
      description: |
        Update on Batch Interface

      body:
        application/json:
          schema: sbatch
          example: |
            [
              {
                "href": "level",
                "rep":
                  {
                    "brightness": 100
                  }
              },
              {
                "href": "colortemperature",
                "rep":
                  {
                    "ct": 4700
                  }
              },
              {
                "href": "ramptime",
                "rep":
                  {
                    "ramptime": 10
                  }
              }
            ]

      responses:
        200:
          description: "all targets returned OK status (HTTP 200 or CoAP 2.04 Changed) return a representation of the current state of all targets"
          body:
            application/json:
              schema: sbatch
              example: |
                [
                  {
                    "href": "level",
                    "rep":
                      {
                        "brightness": 100
                      }
                  },
                  {
                    "href": "colortemperature",
                    "rep":
                      {
                        "ct": 4700
                      }
                  },
                  {
                    "href": "ramptime",
                    "rep":
                      {
                        "ramptime": 10
                      }
                  }
                ]


        403:
          description: "one or more targets did not return OK status; return a retrieve representation of the current state of all targets in the batch"
          body:
            application/json:
              schema: sbatch
              example: |
                [
                  {
                    "href": "level",
                    "rep":
                      {
                        "brightness": 0
                      }
                  }
                ]

/LuminaireLinkListInterfaceURI:
    description: |
      The oic.if.ll interface exposes a representation of the links

    displayName: Link List Representation
    is: [ interface-ll ]

    get:
      description: |
        Retrieve on Link List Interface

      responses:
        200:
          body:
            application/json:
              schema: slinks
              example: |
                {
                  "links": [
                    {
                      "href": "switch",
                      "ins": "switch",
                      "title": "On/Off Switch",
                      "rt":   ["oic.r.binaryswitch"],
                      "if":   ["oic.if.a", "oic.if.baseline"]
                    },
                    {
                      "href": "level",
                      "ins": "level",
                      "title": "Brightness Level",
                      "rt":   ["oic.r.brightness"],
                      "if":   ["oic.if.a", "oic.if.baseline"]
                    },
                    {
                      "href": "colorcontrol",
                      "ins": "colorcontrol",
                      "title": "Color Control",
                      "rt":   ["oic.r.colourchroma"],
                      "if":   ["oic.if.a", "oic.if.baseline"]
                    },
                    {
                      "href": "colortemperature",
                      "ins": "colortemperature",
                      "title": "Color Temperature",
                      "rt":   ["oic.r.colourchroma"],
                      "if":   ["oic.if.a", "oic.if.baseline"]
                    },
                    {
                      "href": "ramptime",
                      "ins": "ramptime",
                      "title": "Ramp Time",
                      "rt":   ["oic.r.ramptime"],
                      "if":   ["oic.if.a", "oic.if.baseline"]
                    },
                    {
                      "href": "actuation",
                      "rel": "actuator",
                      "ins": "actuation",
                      "title": "Actuation",
                      "rt":   ["oic.r.actuation", "oic.r.binaryswitch", "oic.r.brightness", "oic.r.colourchroma", "oic.r.ramptime"],
                      "if":   ["oic.if.a", "oic.if.baseline"]
                    }
                  ]
                }
