#%RAML 0.8
# RAML for OCF mapping of the lwm2m firmware update object.
# Resource type representing a lwm2m firmware update object
#

title: lwm2m firmware update object
version: 0.1
documentation:

  - title: OCF lwm2m firmware update object
    content: |
      OCF mapping of an lwm2m firmware update object
