#%RAML 0.8
# RAML for OCF mapping of the lwm2m server object.
# Resource type representing a lwm2m server object
#

title: lwm2m server object
version: 0.1
documentation:

  - title: OCF lwm2m server object
    content: |
      OCF mapping of an lwm2m server object
