#%RAML 0.8
# RAML for OCF mapping of the lwm2m device object.
# Resource type representing a lwm2m device object
#

title: lwm2m device object
version: 0.1
documentation:

  - title: lwm2m native device object
    content: |
      native mapping of an lwm2m device object

  - title: Introduction
    content: |
      raw definition for LWM2M management object ID number 3, the device object

  - title: Resource Design
    content: |
      one to one mapping of the lwm2m device management attributes to OCF resource properties


schemas:
  - schema-baseline: !include schemas/oic.r.lwm2m.device.schema-baseline.json
  - schema-r: !include schemas/oic.r.lwm2m.device.schema-r.json
  - schema-rw: !include schemas/oic.rw.lwm2m.device.schema-rw.json
  - schema-a: !include schemas/oic.rw.lwm2m.device.schema-a.json

traits:
  - interface-baseline:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

  - interface-r:
      queryParameters:
        if:
          enum: ["oic.if.r"]

  - interface-rw:
      queryParameters:
        if:
          enum: ["oic.if.rw"]

  - interface-a:
      queryParameters:
        if:
          enum: ["oic.if.a"]


/lwm2mDeviceBaselineURI:
  description: |
    The oic.if.baseline interface exposes a representation of
    the links and the properties


  displayName: Device Baseline
  is: [ interface-baseline ]

  get:
    description: |
      Retrieve on Baseline Interface

    responses:
      200:
        body:
          application/json:
            schema: schema-baseline
            example: |
              {
                "rt": ["x-lwm2m.r.device"],
                "if": ["oic.if.baseline", "oic.if.a", "oic.if.r", "oic.if.rw"],
              }


/lwm2mDeviceReadableURI:
    description: |
      The oic.if.r interface exposes a representation of readable properties

    displayName: Readable properties
    is: [ interface-r ]

    get:
      description: |
        Retrieve readable properties

      responses:
        200:
          description: "return the readable properties of the device resource"
          body:
            application/json:
              schema: schema-r
              example: |
                [
                  {
                    "0": "Acme Inc.",
                    "1": "Acme Levitation Suit",
                    "2": "0000001",
                    "3": "0.0.1",
                    "4": false,
                    "5": false,
                    "6": [6, 1],
                    "7": [553.1, 535.2],
                    "8": [17.2, 10.12],
                    "9": 60,
                    "10": 105567,
                    "11": [0],
                    "12": false,
                    "13": 1492128887,
                    "14": -7,
                    "15": "America/San_Francisco",
                    "16": ["U", "UQ"],
                    "17": "prototype",
                    "18": "0.0.1",
                    "19": "0.0.1",
                    "20": 1,
                    "21": 10030445,
                    "22": "http://example.org/mud/acme-levitation-suit.html"
                   }
                ]
